version: "3"
services:
  pgweb:
    image: sosedoff/pgweb
    ports:
      - "4442:8081"
    environment:
      DATABASE_URL: postgres://postgres:pgweb@db:5432/postgres?sslmode=disable
    depends_on:
      - db
  db:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgweb
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"